/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dataloader;

import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import javax.swing.WindowConstants;
import javax.swing.*;
import java.sql.*;  
import java.io.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author vinayak
 */
public class imagesearch extends javax.swing.JFrame implements ActionListener{
jdbcconn conn;
 /**
     * Creates new form imagesearch
     */
public void actionPerformed(ActionEvent e)
{
    String eve=e.getActionCommand();
data2 a=new data2();
        a.getCarWithCarID(Integer.parseInt(eve),"CAR_DATA",conn);
        Data_Disp s=new Data_Disp(a);

}
public void load() throws SQLException, FileNotFoundException, IOException{
int car_id;
jPanel1.setLayout(new GridLayout(100,3));
ResultSet rs=conn.executeQuery("select IMAGE,CAR_ID from CAR_IMAGE ");  
while(rs.next()){//now on 1st row  
     System.out.println("dsf");
JButton btn=new JButton();           
Blob b=rs.getBlob(1);//2 means 2nd column data 
car_id=rs.getInt(2);
byte barr[]=b.getBytes(1,(int)b.length());//1 means first image  
String file="/home/vinayak/mini project data";
file=file.concat("/"+car_id+".jpg");
FileOutputStream fout=new FileOutputStream(file);
//imag=new image(file);
fout.write(barr);  
fout.close();
ImageIcon icon = new ImageIcon(file);
       btn.setIcon(icon);
       btn.setActionCommand(Integer.toString(car_id));
       btn.addActionListener(this);
       jPanel1.add(btn);

//return file;
}
}
    public imagesearch(jdbcconn con) {
        initComponents();
        conn=con;
        try{
            
        load();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setExtendedState( getExtendedState() | JFrame.MAXIMIZED_VERT | Frame.MAXIMIZED_HORIZ);
        }
        catch(Exception e){
        System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
